stages:
  load_data:
     cmd: python src/load_data.py --config=params.yaml
     deps:
     - src/get_data.py
     - src/load_data.py
     - data_given/winequality_red.csv
     outs:
     - data/raw/winequality_red.csv

  split_data:
     cmd: python src/split_data.py --config=params.yaml
     deps:
     - src/split_data.py
     - data/raw/winequality_red.csv
     outs:
     - data/processed/train_winequality_red.csv
     - data/processed/test_winequality_red.csv

  train_and_evaluate:
     cmd: python src/train_and_evaluation.py --config=params.yaml
     deps:
     - data/processed/train_winequality_red.csv
     - data/processed/test_winequality_red.csv 
     - src/train_and_evaluation.py
     params:
     - estimators.ElasticNet.params.alpha
     - estimators.ElasticNet.params.l1_ratio
     metrics:
     - reports/metrics.json:
          cache: false
     - reports/params.json:
          cache: false

 