stages:
  load_data:
     cmd: python src/load_data.py --config=params.yaml
     deps:
     - src/get_data.py
     - src/load_data.py
     - data_given/winequality_red.csv
     outs:
     - data/raw/winequality_red.csv

  split_data:
     cmd: python src/split_data.py --config=params.yaml
     deps:
     - src/split_data.py
     - data/raw/winequality_red.csv
     outs:
     - data/processed/train_winequality_red.csv
     - data/processed/test_winequality_red.csv